name: Battlegrounds
version: "${project.version}"
main: com.emirkabal.battlegrounds.Main
commands:
  report:
    description: "Report a player"
  setposition:
    description: "setposition"
    aliases: ["setspawn", "setpos"]
  getposition:
    description: "getposition"
    aliases: ["getpos", "spawn"]
  getworld:
  addworld:
  removeworld:
  changeworld:
  setsafelocation:
  stats:
  win:
  timer:
  ping:
    description: "Calculate player's latency"
    aliases: ["latency"]
